apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata: 
  name: webcolor-success
spec: 
  metrics: 
    - name: success-rate
      interval: 30s
      count: 6
      successCondition: result > 0.9
      failureCondition: resul < 0.8
      provider: 
        prometheus: 
          address: http://prometheus-server.monitoramento.svc.cluster.local
          query: |
            scalar(
              sum(rate(flask_http_request_total{app="webcolor-canary",status=~"2.."}[2m]))
              /
              sum(rate(flask_http_request_total{app="webcolor-canary"}[2m]))
            )
