apiVersion: v1
kind: Service
metadata:
  name: webcolor
spec:
  selector:
    app: webcolor
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: LoadBalancer

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: webcolor
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webcolor

  template:
    metadata:
      labels:
        app: webcolor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"

    spec:
      containers:
        - name: webcolor
          image: fabricioveronez/web-color:green
          ports:
            - containerPort: 80

  minReadySeconds: 30

  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: {}
        - setWeight: 50
        - analysis:
            - templateName: webcolor-success
        - setWeight: 75
        - analysis:
            - templateName: webcolor-success
        - setWeight: 100